### PR TITLE
Merge development branch into master for sprint 7

### PR DESCRIPTION
**Pull request by Faffie**
Request to pull development branch into master branch for the sprint 7 release (BETA).

### CODE REVIEW

**Comment by Faffie** [comment]
https://github.com/alanvanrossum/kroket/pull/45
https://github.com/alanvanrossum/krokethost/pull/19
https://github.com/alanvanrossum/kroketapp/pull/36

**Comment by Mayke93** [comment]
This branch consist of pull requests that were already checked, so it is good for merging.

**Comment by irenevanderblij** [comment]
Travis CI is failing

**Comment by irenevanderblij** [comment]
Agreed, let's merge!

**Pull request merged**
