### PR TITLE
Minigamef

### PR DESCRIPTION
**Pull request by irenevanderblij**
Host implementation of minigame F!

Test together with the app and VR game.

### CODE REVIEW

**Comment by irenevanderblij** [comment]
I refactored minigame F to be named minigame D, since this is the logical sequence after C. The Waiting minigame (before game D) is fully refactored to waiting.

Please review (and merge)

**Comment by Faffie** [comment]
I have no remarks about the actual code. 

Formatting and indentation seem off but you already explained why, doesn't matter though.

**Comment by Faffie** [comment]
Things seem to work fine and code-wise this is another variation of what we already had in place. I wouldn't mind having this merged.

**Comment by alanvanrossum** [comment]
Awesome job on getting the VR side game ready, i;ll test this and merge it!

**Comment by Mayke93** [comment]
we've tested it so we can merge

**Pull request merged**
