### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Mayke93**
most testable aspects of server are now tested.

### CODE REVIEW

**Comment by Faffie** [comment]
Tests seem good, I disagree with the naming though.

**Comment by harveyvanveltom** [comment]
Nice tests. can be merged(though the naming could be improved)

**Comment by Mayke93** [comment]
I have changed the names

**Comment by Faffie** [comment]
Looks great.

**Comment by irenevanderblij** [comment]
Nice testing, I will merge.

**Pull request merged**
