### PR TITLE
Able to have multiple sessions on the same host.

### PR DESCRIPTION
**Pull request by irenevanderblij**
When a game is won or lost, a new session starts automatically. When players connect to the game, they connect to the newest session. The session starts when enough players are connected in the new session..

The VR side still shows the total amount of players connected to the game, instead of only this session (but this has to do with the VR not the host).

### CODE REVIEW

**Comment by alanvanrossum** [comment]
Javadoc is one of those things in life you just can't get enough of. Awesome job!

**Comment by irenevanderblij** [comment]
Thanks for fixing the tests :+1:

**Comment by Faffie** [comment]
Listing the amount of players connected to the server was the original intent. This is fine to me.

**Comment by Faffie** [comment]
Also, thanks for fixing the tests. :cactus:

**Comment by alanvanrossum** [comment]
Nice, this should make demoing the game a lot easier, as we won't have to restart the host after every game.

**Pull request merged**
