### PR TITLE
Refactor protocol & state handling

### PR DESCRIPTION
**Pull request by Faffie**
Refactored the host:
Changed the gamestates. 
Updated architecture.
Fixed package declaration.
Applied formatting.
Updated protocol.
Implemented game sessions.

Please review & merge.

### CODE REVIEW

**Comment by alanvanrossum** [comment]
Nice refactor. Quite a large PR. I see you got rid of most of the static methods and implemented a seperate gamesession. The architecture makes more sense now and should be easier to maintain/extend.
Has the protocol been changed in the clients yet?

**Comment by Faffie** [comment]
Thanks. I have a PR open for both. All three should be merged at once or things will break. I couldn't keep it backwards compatible and I really didn't want to.

**Comment by irenevanderblij** [comment]
StateA and StateNone have the same javadoc comment, which would mean that they are both states that can start and end minigame A. That is probably not the case, right?

**Comment by irenevanderblij** [comment]
Did you test this? In your refactor you can just start minigame B when minigame A is not even started...

**Comment by irenevanderblij** [comment]
Minigame C does not work anymore. I cannot start the colorsequence on the app. Guess that is going wrong here? Not sure, don't feel like it is my job to find out.

**Comment by Mayke93** [comment]
You can also do minigame a and b, and then a again. 
Minigame B is also broken, both smartphone players need to complete this, and this is not the case in this refactor. Minigame c does not work anymore.

**Comment by Mayke93** [comment]
Also, the vr client still seems to send an INITM message with doneC. The host seems to receive this multiple times, or at least it gives the messages 
"[11:12:39]: ERROR ClientInstance: Invalid command : INITM
[11:12:39]: INFO ClientInstance: Input received: INITM[doneC]" on sort of loop.

Minigame C was not even finished at the time these messages were appearently sent. This did not happen before.

**Comment by Faffie** [comment]
Perhaps I was too early throwing this PR out, because I knew a few things wouldn't work as expected. I wanted to discuss everything during our meeting and see what I missed so I can change that. Making it work as expected really should be easy.

**Comment by Faffie** [comment]
Ignore the Javadoc for now. Seriously, how can you blame me for breaking this? If you build a house of cards, don't expect it to survive a tornado. This was only a gentle breeze for that matter. 

:tired_face: 

States now progress according to the predefined order. Expanding should be easy. Because C is being altered right now this still is a work in progress.

A and B work as expected, what happens after completing C is undefined.

**Comment by Faffie** [comment]
Again: what happens after C is UNDEFINED. That means it's not defined. It still has to be added. I don't know what I'm supposed to add, though. Please just test it and ignore what happens after C.

**Comment by irenevanderblij** [comment]
Thanks for updating the refactor. Everything seems to work now :) 

After minigame B has been merged, all conflicts can be resolved and this can be merged aswell!

**Comment by Faffie** [comment]
Tested. Ready to be merged. If you're too lazy to test everything yourself, just watch the video I sent.

**Comment by harveyvanveltom** [comment]
I don't see a verification message being sent to the vr client in stateB. right now if both mobile players beat the game minigame B is completed. but this shouldn't be the case. if both mobile players beat minigame B it should send a check to the VR client. and only if he also completed minigameB minigame B can be completed.

**Comment by Faffie** [comment]
You're absolutely right. Fixed that.

**Comment by harveyvanveltom** [comment]
Well done it looks like Minigame B is working as was intended now. I really like your changes to the protocol makes the messages and therefore the methods that use them a lot clearer and easier to read. can be safely merged

**Comment by Faffie** [comment]
Thanks. I have no idea why it got out of hand so rapidly before. This was incredibly painful to fix and could (SHOULD) have been prevented. I hope this helps as far as damage control goes.

**Pull request merged**
