### PR TITLE
Send done to the mobile client when minigame C is done

### PR DESCRIPTION
**Pull request by irenevanderblij**
Send done to the mobile player instead of virtual player

### CODE REVIEW

**Comment by Mayke93** [comment]
very small change, it works.

**Comment by Faffie** [comment]
How are you expecting anyone to review this huge  pile of code?

Seriously though, I don't think creating a branch and going through the trouble of making a PR and having it reviewed is really necessary for changes like this, and I don't think it's worth the time/trouble. As you're not adding functionality but merely fixing mistakes in code, I don't think pushing such changes to development directly is a big deal to anyone.

**Comment by Faffie** [comment]
The merge button doesn't work in my mobile browser!

**Comment by Faffie** [comment]
Done

**Pull request merged**
